### ISSUE TITLE
Installing package in mac fails if python3 is used

### ISSUE THREAD

**Issue by llali** [microsoft/sqlmlutils#54]
I'm using python3 in mac and when I use sqlmlutils to install package it fails. The issue is in this file https://github.com/microsoft/sqlmlutils/blob/master/Python/sqlmlutils/packagemanagement/pipdownloader.py line 48. there's a process run to download the packages but using "python" as executable but in my mac the executable is python3. instead of hard coding to 'python' it use get the executable from  sys.executable

**Comment by JonathanZhu11** [comment]
Fixed in PR #59
